# values.yaml
replicaCount: 1

image:
  repository: apache/activemq-artemis
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

secrets:
  - name: ARTEMIS_USER
    secret_key: ARTEMIS_USER
    secret_name: activemq-artemis-secret

  - name: ARTEMIS_PASSWORD
    secret_key: ARTEMIS_PASSWORD
    secret_name: activemq-artemis-secret

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 61613

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: activemq-artemis.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  requests:
    cpu: 20m

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
